services:
  development:
    env_file: .devcontainer/devcontainer.env
    build:
      context: .
      # relative to first file in "dockerComposeFile" array
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # relative to first file in "dockerComposeFile" array
      - .:/code:cached

    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
